language: python
sudo: false
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install -r tests/requirements.txt -r doc/requirements.txt
- python setup.py install
script:
- py.test
- pushd doc && make html && popd
deploy:
  provider: pypi
  distributions: sdist bdist_wheel --universal
  docs_dir: doc/.build/html
  user: marvint
  password: ${PYPI_PASSWORD}
  skip_cleanup: true
  on:
    tags: true
    python: '2.7'
